### ISSUE TITLE
Event notifications don't work

### ISSUE THREAD

**Issue by shurakenas** [dmitrijkir/mattermost-plugin-calendar#21] opened 2023-11-08 12:23 UTC
I create an event, but the notification does not come, is this how it should be?

**Comment by dmitrijkir** [comment] 2023-11-08 13:19
Defenetly not. Check the logs if an error happens. I'll try to reproduce it if you share your event from the database (calendar_events) and plugin version.

**Comment by shurakenas** [comment] 2023-11-08 14:17
```
                  id                  |     title      |        start        |         end         |          created           |           owner            | channel | processed | recurrence | recurrent |  color  | description
--------------------------------------+----------------+---------------------+---------------------+----------------------------+----------------------------+---------+-----------+------------+-----------+---------+-------------
116d9807-fd57-4d7c-bc9d-f35c94057f12 | тест2          | 2023-11-08 15:00:00 | 2023-11-08 15:30:00 | 2023-11-08 14:07:04.49202  | yaqu1c3d838b5kzsnsetgtd6hh |         |           |            | f         | #D0D0D0 |

```

I understood what was wrong, the time is counted incorrectly, but I do not know how to fix it, I will be glad if you help.

In this example, I created the event start - 18:00, end - 18:30, but as you can see from the line in the database, the time differs by 3 hours.

And also, if you look at the screenshot, you can see by the color that the working day is incorrectly determined.
https://ibb.co/Y8pXgk9

Plugin version 0.4.3, tried version 0.5.0.

**Comment by shurakenas** [comment] 2023-11-08 14:29
Is it possible to choose a time zone?

**Comment by shurakenas** [comment] 2023-11-08 14:33
```
{
  "caller": "app/plugin_api.go:976",
  "level": "error",
  "msg": "CreateGroupChannel: Group message channels must contain at least 3 and no more than 8 users., ",
  "plugin_id": "com.dmkir.calendar",
  "timestamp": "2023-11-08 17:30:01.276 +03:00"
}

```

I set the time of the event based on UTC, but the notification did not work

**Comment by dmitrijkir** [comment] 2023-11-08 17:11
It's ok, all events are stored in UTC. However, I get an error, there are more than eight users, and Mattermost can't create a group for notifications. Try Crete channel, it should work. In the next release, I'll send direct notifications to all members, if there are more than 8

**Comment by shurakenas** [comment] 2023-11-08 17:51
Is it possible to add the option to select UTC?
Not really, what does the Crete channel mean?
I chose only one user, not eight.

**Comment by dmitrijkir** [comment] 2023-11-08 18:32
When you create an event, the plugin converts your local time to UTC and stores it. Notifications are based on UTC time. I don't believe this should be a problem right now.

I suggest creating a channel and selecting it as the channel for the event.

I've analyzed the error, and it seems that the plugin is attempting to send notifications but is unable to create a group. When you choose members without selecting a channel, the plugin automatically creates a group for notifications and sends messages to that group.

Out of curiosity, which version of Mattermost are you currently using?

**Comment by shurakenas** [comment] 2023-11-08 19:04
I use version 8.1.4.
When I create an event, for example, with the beginning at 18:00, the beginning is displayed in the database at 15:00, respectively, nothing is converted as you say, or did I understand something wrong?

**Comment by shurakenas** [comment] 2023-11-08 19:43
To create an event for a while, you have to calculate the time based on UTC, this is not very convenient for users, ordinary users will be confused, how can this problem be solved? I will be very grateful for your work.

**Comment by dmitrijkir** [comment] 2023-11-08 19:55
When you create an event that starts at 18:00 and your time zone is UTC+3, it means that the time stored in the database will be 15:00.

When you open the calendar and retrieve an event, the plugin takes an event with a starting time of 15:00, adds your time zone offset of +3 hours, and displays it as 18:00. This is why your event appears in its correct place on the calendar.

In the background, there's a job that fetches all events from the database that are scheduled to start at the job's UTC time. For instance, if the job starts at 15:00 UTC, in your time zone, it would be 18:00.

I noticed the error you encountered, the plugin attempted to send a notification but was unable to create a group channel for it.

As the error message suggests, I believe the issue may be related to the number of members in this event, which should ideally range from 3 to 8. By default, the plugin adds the event organizer and the calendar bot.

**Comment by dmitrijkir** [comment] 2023-11-08 20:04
> To create an event for a while, you have to calculate the time based on UTC, this is not very convenient for users, ordinary users will be confused, how can this problem be solved? I will be very grateful for your work.


Regular users shouldn't need to keep an eye on the database to understand how it works.

**Comment by shurakenas** [comment] 2023-11-08 20:05
no, it's not, I'll give you an example: now it's 18:00, I'm creating an event starting at 20:00, in the database it will be 17:00 (minus 3), respectively, the plugin believes that the time has passed, there will be no notification.

**Comment by dmitrijkir** [comment] 2023-11-08 20:12
If your current time is 18:00, and you create an event for 20:00, the event's start time in the database will be 17:00, which is correct. However, the current time in the plugin will be 15:00, which means that notifications should be scheduled for the future.

**Comment by shurakenas** [comment] 2023-11-08 20:17
yes, this is a complete confusion, how to understand it?

**Comment by dmitrijkir** [comment] 2023-11-08 20:21
My time zone is UTC+3. I scheduled an event to start at 00:17, but it got saved in the database as 2023-11-08 20:17:00.000. I received a notification at 00:17 in my local time.

<img width="599" alt="Screenshot 2023-11-09 at 00 16 37" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/9cef6218-31f6-4659-a8e5-c0f9449f34ec">

<img width="202" alt="Screenshot 2023-11-09 at 00 17 02" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/da95b94a-25e4-4c09-81a1-c429ab3b2e9d">
<img width="638" alt="Screenshot 2023-11-09 at 00 16 47" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/80e3b52c-b482-47a7-8f2d-e47265049cd2">
<img width="983" alt="Screenshot 2023-11-09 at 00 17 16" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/da4482b3-bee9-4892-a360-7ea6eb38be78">

**Comment by shurakenas** [comment] 2023-11-08 20:27
if I create an event at 20:00, then it should be at 20:00, and not at 17:00, this is inconvenient, users need to make an error of 3 hours at UTC +3, not a user friend at all, a simple user will not use this

**Comment by shurakenas** [comment] 2023-11-08 20:32
> My time zone is UTC+3. I scheduled an event to start at 00:17, but it got saved in the database as 2023-11-08 20:17:00.000. I received a notification at 00:17 in my local time.
> 
> <img width="599" alt="Screenshot 2023-11-09 at 00 16 37" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/9cef6218-31f6-4659-a8e5-c0f9449f34ec">
> 
> <img width="202" alt="Screenshot 2023-11-09 at 00 17 02" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/da95b94a-25e4-4c09-81a1-c429ab3b2e9d">
> <img width="638" alt="Screenshot 2023-11-09 at 00 16 47" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/80e3b52c-b482-47a7-8f2d-e47265049cd2">
> <img width="983" alt="Screenshot 2023-11-09 at 00 17 16" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/da4482b3-bee9-4892-a360-7ea6eb38be78">
> 
> 
> 

I do not receive any notifications in this scenario, the logs are empty, respectively, the event does not occur

**Comment by dmitrijkir** [comment] 2023-11-08 20:36
I believe there might be a misunderstanding. When you create an event for 20:00, you should receive a notification at 20:00, just as I demonstrated. The event's UTC time is primarily for storage purposes, and I mentioned it in response to your question about the time difference in the database.

Ordinary users who use this calendar shouldn't need to concern themselves with these technical details.

Your issue seems to have a different nature, and it's not related to the event time

**Comment by shurakenas** [comment] 2023-11-08 20:40
then why doesn't the event occur? 
if I set the start time of the event with an error with my UTC +3 so that it matches in the database with my time, then the event occurs

**Comment by dmitrijkir** [comment] 2023-11-08 20:49
I'll attempt to install the same version of Mattermost as yours and try to replicate this error. It's possible that this particular version may have some bugs related to users time zones.

It shouldn't work in the same way as it does on your system.

**Comment by dmitrijkir** [comment] 2023-11-08 21:03
I believe I understand now. It seems that the server where Mattermost is deployed is not set to the UTC time zone, which is causing the discrepancy in the event timing and the database records. This can lead to notifications being delivered at a different time than expected in your local time zone.

**Comment by dmitrijkir** [comment] 2023-11-08 21:06
If that's correct, you can change the server's timezone to UTC while I figure out how to address this issue in the future.

**Comment by shurakenas** [comment] 2023-11-09 05:33
the UTC time zone is set on the server
```
timedatectl
               Local time: Чт 2023-11-09 08:32:00 MSK
           Universal time: Чт 2023-11-09 05:32:00 UTC
                 RTC time: Чт 2023-11-09 05:32:01
                Time zone: Europe/Moscow (MSK, +0300)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no
```

**Comment by shurakenas** [comment] 2023-11-09 06:26
for the experiment, I made a local time with the UTC time zone, the events still do not start

**Comment by dmitrijkir** [comment] 2023-11-09 09:46
I'll make some adjustments, and then we can give it another try.

**Comment by shurakenas** [comment] 2023-11-09 09:47
Thank you, I'll be waiting

**Comment by dmitrijkir** [comment] 2023-11-12 08:19
Give this new release a shot—I hope it proves helpful! https://github.com/dmitrijkir/mattermost-plugin-calendar/releases/tag/0.5.0-rc2

**Comment by shurakenas** [comment] 2023-11-13 04:23
nothing has changed, the events do not start due to not matching the time

**Comment by dmitrijkir** [comment] 2023-11-14 21:28
I have no idea why this isn't working. I tried installing your version of the application, experimented with changing the time zone only in the application and then in the database, set different time zones for them, set identical ones different from the local one. I couldn't reproduce such behavior. Every time, I received a notification at the time specified in the event. I even tried with Docker and without. I don't understand why this might not be working. 😢

**Comment by shurakenas** [comment] 2023-11-15 05:37
I realized what the problem is, it doesn't work when I use the 24-hour format, if the 12-hour format, then everything is fine.

Now the question is, is it possible to make a correction to work with the 24-hour format? If it is not possible, then I think it is worth adding to the documentation that you need to use the 12-hour format.

**Comment by dmitrijkir** [comment] 2023-11-15 08:36
Where did you change the time format? I use the 24-hour format in the system and in the Mattermost client, but I tried changing it to the 12-hour format on the client, and nothing changed. Continues to work.

**Comment by shurakenas** [comment] 2023-11-15 08:39
Я менял в клиенте.
<img width="591" alt="Снимок экрана 2023-11-15 113814" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/45785038/c61a5477-bfee-40bb-834f-3fd2d46185e0">

**Comment by shurakenas** [comment] 2023-11-15 08:41
> > Мой часовой пояс — UTC+3. Я запланировал начало события в 00:17, но оно было сохранено в базе данных как 2023-11-08 20:17:00.000. Я получил уведомление в 00:17 по местному времени.
> > <img alt="Скриншот 09.11.2023, 00 16 37" width="599" src="https://user-images.githubusercontent.com/22306239/281532439-9cef6218-31f6-4659-a8e5-c0f9449f34ec.png">
> > <img alt="Скриншот 09.11.2023, 00 17 02" width="202" src="https://user-images.githubusercontent.com/22306239/281532513-da95b94a-25e4-4c09-81a1-c429ab3b2e9d.png">
> > <img alt="Скриншот 09.11.2023, 00 16 47" width="638" src="https://user-images.githubusercontent.com/22306239/281532553-80e3b52c-b482-47a7-8f2d-e47265049cd2.png">
> > <img alt="Скриншот 09.11.2023, 00 17 16" width="983" src="https://user-images.githubusercontent.com/22306239/281532590-da4482b3-bee9-4892-a360-7ea6eb38be78.png">
> 
> Никаких уведомлений в этом сценарии я не получаю, логи пустые, соответственно событие не происходит

Here you can see in the screenshots that you are using the 12 hour format

**Comment by dmitrijkir** [comment] 2023-11-15 09:05
In the screenshot, yes, it's in the 12-hour format. But I tried changing it to different formats. On my production setup, I use the 24-hour format. Tried changing it on the test environment, and it seems fine. Write to me on Telegram @dmitrijkir, let's think about how else we can check this, if you want))
<img width="573" alt="Screenshot 2023-11-15 at 13 02 05" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/88cfd0a1-f5c1-4826-b878-7cd51682eac3">

<img width="258" alt="Screenshot 2023-11-15 at 13 01 22" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/c3081b90-8974-4e81-ab49-27206cb295ed">
<img width="790" alt="Screenshot 2023-11-15 at 13 01 28" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/22306239/64d02295-be9d-40e9-b2e8-4a543159d944">

**Comment by shurakenas** [comment] 2023-11-15 12:37
<img width="196" alt="Снимок экрана 2023-11-15 153605" src="https://github.com/dmitrijkir/mattermost-plugin-calendar/assets/45785038/cd5f0940-50c8-4463-83f8-43d2adff0933">
I returned to the 24-hour format, checked again, now it works, I don't understand what the problem was

**Comment by dmitrijkir** [comment] 2023-11-15 14:00
Good news, it's great that everything is working. I'm closing the issue.

**Closed by dmitrijkir** 2023-11-15 14:00 UTC
